version: "3"

services:
  initial_node:
    image: multichain
    build: .
    container_name: multichain_initial_node
    command: /bin/bash -c "multichain-util create chain1; multichaind chain1 -daemon -port=7721 -rpcport=7720 && tail -f /dev/null"
    networks:
    - multichain
  node:
    image: multichain
    build: .
    command: /bin/bash -c "multichaind -daemon chain1@multichain_initial_node:7721 && tail -f /dev/null"
    depends_on:
    - initial_node
    networks:
    - multichain
    
networks:
  multichain:
    driver: bridge